// <auto-generated />
using System;
using AntOptimization.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AntOptimization.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.15");

            modelBuilder.Entity("AntOptimization.Domain.Entities.CompareRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("LocationCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StartLocationIndex")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.ToTable("CompareRuns");
                });

            modelBuilder.Entity("AntOptimization.Domain.Entities.CompareRunResult", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Algorithm")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("BestRouteOrderJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompareRunId")
                        .HasColumnType("TEXT");

                    b.Property<long>("ExecutionTimeMs")
                        .HasColumnType("INTEGER");

                    b.Property<double>("RelativeGapPercent")
                        .HasColumnType("REAL");

                    b.Property<string>("RouteCoordinatesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("TotalDistanceKm")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("CompareRunId");

                    b.ToTable("CompareRunResults");
                });

            modelBuilder.Entity("AntOptimization.Domain.Entities.OptimizationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BestRouteOrderJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("LocationCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RouteCoordinatesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("StartLocationIndex")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TotalDistanceKm")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.ToTable("OptimizationRuns");
                });

            modelBuilder.Entity("AntOptimization.Domain.Entities.CompareRunResult", b =>
                {
                    b.HasOne("AntOptimization.Domain.Entities.CompareRun", "CompareRun")
                        .WithMany("Results")
                        .HasForeignKey("CompareRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompareRun");
                });

            modelBuilder.Entity("AntOptimization.Domain.Entities.CompareRun", b =>
                {
                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
